version: '3.8'

services:
  sqlite:
    image: nouchka/sqlite3
    container_name: sqlite-container
    volumes:
      - ./data:/data  # Make sure Docker has permission to access this path
    ports:
      - "8080:8080"  # Optional: Expose a port if needed
    restart: always

volumes:
  sqlite-data: